// {amount} and {ticker} get substituted at send-time. Keep entries short —
// buyer wallet + Solscan link are appended after, and the combined tweet
// must stay under Twitter's 280-char limit (enforced/truncated in server.js).
module.exports = [
  '🚀 {amount} SOL just aped into {ticker}! Another W for the army 💪',
  '🐋 Whale alert! {amount} SOL buy on {ticker}. Chart looking bullish af 📈',
  '💎 Diamond hands loading... {amount} SOL just went into {ticker}. WAGMI 🙌',
  '🔥 {amount} SOL BUY on {ticker}! This is the way. To the moon 🌙',
  '⚡️ Printer go brrr — {amount} SOL scooped up on {ticker}. Few understand 👀',
  '🦍 Ape strong together. {amount} SOL just bought {ticker}. Send it 🚀',
  '📈 {ticker} update: +{amount} SOL buy just landed. NFA but... wagmi',
  '👑 King move: {amount} SOL into {ticker}. Bulls eating good today 🍽️',
  '🌙 Moon mission status: fueled by {amount} SOL on {ticker}. Buckle up 🚀',
  '💰 Fresh {amount} SOL buy on {ticker}. Smart money loading bags 🎒',
  '🚨 Buy alert: {amount} SOL just entered {ticker}. This one is cooking 🔥',
  '🐳 Big fish spotted. {amount} SOL buy on {ticker}. Ripples incoming 🌊',
  '🎯 {amount} SOL landed on {ticker}. Precision entry. LFG 🚀',
  '💪 {ticker} holders stay winning. +{amount} SOL just bought in 📊',
  '🧠 Few see it coming. {amount} SOL just aped {ticker}. Alpha detected 🕵️',
  '🔋 {ticker} getting charged up — {amount} SOL buy just hit. Power move ⚡️',
  '🏗️ Building the {ticker} army one buy at a time. +{amount} SOL just in 🧱',
  '🐂 Bulls confirmed. {amount} SOL buy on {ticker}. Charts don\'t lie 📈',
  '🎢 {ticker} only goes up from here. {amount} SOL just aped in 🎡',
  '🥇 Another day, another {ticker} W. {amount} SOL buy secured 🏆',
  '🛸 {amount} SOL just abducted into {ticker}. Aliens are bullish too 👽',
  '🍀 Lucky buyer aped {amount} SOL into {ticker}. Fortune favors the bold 🎲',
  '📡 Signal received: {amount} SOL buy on {ticker}. Bags loading... 🎒',
  '🧨 {amount} SOL just detonated on {ticker}. Explosive momentum 💥',
  '🏄 Riding the {ticker} wave. {amount} SOL buy just dropped in 🌊',
  '🕹️ {ticker} on god mode. {amount} SOL buy just entered the chat 🎮',
  '🌪️ {amount} SOL storm just hit {ticker}. Hold on tight 🌀',
  '🔑 Unlocking gains. {amount} SOL just bought {ticker}. Keys to the moon 🗝️',
  '🍯 Sweet buy alert: {amount} SOL into {ticker}. Bears getting rekt 🐻',
  '🎉 {ticker} party continues. {amount} SOL just joined the buy side 🥳',
  '🚂 All aboard the {ticker} hype train. {amount} SOL just hopped on 🚄',
  '🧊 Ice cold entry. {amount} SOL just bought {ticker} at a steal 🥶',
  '🏹 Bullseye. {amount} SOL just aped {ticker}. Straight to the moon 🎯',
  '🌊 Liquidity wave incoming. {amount} SOL just bought {ticker} 🐬',
  '🎮 {ticker} leveling up. {amount} SOL buy just landed. New high score 🏅',
  '🧬 {ticker} DNA confirmed bullish. {amount} SOL just aped in 🔬',
  '🕯️ Green candle loading. {amount} SOL just bought {ticker} 📈',
  '🏆 Champion move. {amount} SOL into {ticker}. This is a W 🥇',
  '🌌 {ticker} going interstellar. {amount} SOL buy just fueled the rocket 🚀',
  '🦾 Strong hands only. {amount} SOL just bought {ticker}. No paper here 🚫',
  '🎇 {amount} SOL fireworks on {ticker}. Send it to the moon 🎆',
  '🐉 Dragon energy. {amount} SOL just aped {ticker}. Dracarys 🔥',
  '🛰️ {ticker} orbit achieved. {amount} SOL buy just locked in 🛸',
  '🍾 Pop off! {amount} SOL just bought {ticker}. Celebration mode 🎊',
  '🧲 {ticker} pulling in buyers. {amount} SOL just got magnetized 🧲',
  '🐺 Wolves are buying. {amount} SOL just entered {ticker}. Pack growing 🐾',
  '🏰 {ticker} kingdom expands. {amount} SOL buy just secured the throne 👑',
  '🌋 {ticker} erupting. {amount} SOL just triggered the volcano 🔥',
  '🎊 New buyer, who dis? {amount} SOL just aped {ticker}. Welcome fren 🤝',
  '🚀 {amount} SOL says {ticker} is going to the moon. Buckle up frens 🌙',
];
